### PR TITLE
Fix focus area render for QtCreator 17, make lines in tooltip pixel perfect

### LINKED ISSUE #4: Highlighted block bad render in QtCreator 17
Since QtCreator 17 (I think), the highlighted block in the minimap is not rendered correctly. It seems to fill the whole map when in the middle of the code, and visibly shrinks to 0 up or down when approaching respectively the start and end of code.  

I am investigating and did not try anything yet, but I have my suspicion on [this commit](https://code.qt.io/cgit/qt-creator/qt-creator.git/commit/?id=0d22ef1aeef94b22731b372eb4f87cd05ebdb55b) that connects `QScrollBar::valueChanged` to a `position` lambda in `texteditor/texteditor.cpp`. If you have more insight, feel free to share.

I'll post a PR if I can fix it.

### PR DESCRIPTION
**Pull request by Kidev**
- The latest QtCreator version (17) changed `TextEditorWidget` (inside `texteditor.cpp`), that went from inheriting `QPlainTextEdit` to `Utils::PlainTextEdit`.  
This adapts the plugin so that the rendering of the focus area of the minimap is working again, by using the methods from `Utils::PlainTextEdit` (mainly `blockCount` instead of `size` to get the line count). Fixes #4. 

- The line numbers displayed in the tooltip on the minimap were slightly off, and it became worse with QtCreator 17.  
This changes the way the line numbers are computed and make it pixel perfect

- Fix some format errors

### CODE REVIEW

File: minimapstyle.cpp [hunk 1]
```diff
@@ -444,20 +446,51 @@ class MinimapStyleObject : public QObject
...
+            realValue = qMax(0, qMin(realValue, maxSliderTop));
+        }
+
+        if (realValue + viewPortLineCount > actualContentHeight) {
+            realValue = actualContentHeight - viewPortLineCount;
+        }
+        realValue = qMax(0, realValue);
+
+        m_addPage = (realValue + viewPortLineCount < h) ?
+        QRect(0, realValue + viewPortLineCount, w, h - realValue - viewPortLineCount) :
```
Comment (Maddimax) [inline minimapstyle.cpp:487]: This seems like it doesn't do anything?

File: minimapstyle.cpp [hunk 2]
```diff
@@ -444,20 +446,51 @@ class MinimapStyleObject : public QObject
...
+        QRect();
+        m_subPage = (realValue > 0) ?
+        QRect(0, 0, w, realValue) :
+        QRect();
```
Comment (Maddimax) [inline minimapstyle.cpp]: Can we format these so its more obvious that these are ternary operator statements? :)

Comment (Kidev) [reply minimapstyle.cpp]: Oops I was playing with clangformat and did not notice

**Comment by cristianadam** [comment]
Thank you!
